AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/LineLength:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Naming/FileName:
  Exclude:
    - 'lib/rack/override-path.rb'

Style/Documentation:
  Enabled: false